### ISSUE TITLE
Compiling for Windows?

### ISSUE THREAD

**Issue by DimensionDevices** [cprussin/minichrome#32]
Is this possible?

**Comment by cprussin** [comment]
You can try (it should work, afaik all the tools I built this on support windows), but I in no way guarantee or can maintain windows support. Sorry!

I'm happy to accept any PRs necessary to make it work!

**Comment by neurofluxation** [comment]
I wouldn't even know where to start in setting up the tools in Windows tbh :/

**Comment by DimensionDevices** [comment]
So, I have everything installed but I've no idea why "yarn package" won't run.. Any clues?

**Comment by cprussin** [comment]
Ah, sorry the readme is a bit out of date.  As of [this change](https://github.com/cprussin/minichrome/commit/8384185254da87c67802bdf6d39a0567da5369b6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) the yarn scripts are no longer used, you'll want to take a look at the [Makefile](https://github.com/cprussin/minichrome/blob/master/Makefile) and do the equivalent to the `install` target (you won't want exactly that target because it uses the output directory that electron packager generates for a linux build, but the steps for windows will likely be nearly identical).  Good luck!
